#!/bin/bash
apt install curl -y
curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
apt upgrade -y
apt update -y
apt install openjdk-11-jdk -y
apt install net-tools -y
apt update -y
apt install jenkins -y
service jenkins status
service jenkins start
service jenkins status
apt install ufw -y
ufw allow 8080
ufw enbable